use std::fs;
use std::path::Path;

use assert_cmd::prelude::*;
use predicates::prelude::*;
use tempfile::tempdir;

fn setup_fixture() -> (tempfile::TempDir, String, String, String) {
    let dir = tempdir().expect("tempdir");
    let cad_source = dir.path().join("cad_source");
    let components = cad_source.join("components");
    fs::create_dir_all(&components).unwrap();
    let sample_pas = components.join("sample.pas");
    fs::write(
        &sample_pas,
        r#"
unit sample;
interface
{REGISTEROBJECTTYPE FooType}
{REGISTEROBJECTWITHOUTCONSTRUCTORTYPE BarType}
{REGISTERRECORDTYPE BazRecord}
implementation
end.
"#,
    )
    .unwrap();

    let typeexporter_dir = dir.path().join("environment").join("typeexporter");
    fs::create_dir_all(&typeexporter_dir).unwrap();
    let process_file = typeexporter_dir.join("zcad.files");
    fs::write(&process_file, "components/sample.pas\n").unwrap();

    let autogen_dir = cad_source.join("autogenerated");
    fs::create_dir_all(&autogen_dir).unwrap();

    (
        dir,
        cad_source.to_string_lossy().into_owned(),
        process_file.to_string_lossy().into_owned(),
        autogen_dir.to_string_lossy().into_owned(),
    )
}

#[test]
fn typeexport_generates_expected_inc_files() {
    let (_dir, cad_source, process_file, autogen_dir) = setup_fixture();

    let mut cmd = std::process::Command::new(assert_cmd::cargo::cargo_bin!("runtime-builder"));
    cmd.args([
        "typeexport",
        "--path-prefix",
        &cad_source,
        "--process-file",
        &process_file,
        "--autogen-dir",
        &autogen_dir,
    ]);
    cmd.assert()
        .success()
        .stdout(predicate::str::contains("识别到 3 个注册标记"));

    let allgenerated =
        fs::read_to_string(Path::new(&autogen_dir).join("allgeneratedfiles.inc")).unwrap();
    assert_eq!(allgenerated, "aregFooType,\naregBarType,\naregBazRecord,\n");

    let buildmode = fs::read_to_string(Path::new(&autogen_dir).join("buildmode.inc")).unwrap();
    assert_eq!(buildmode, "{}\n");

    let mut cmd = std::process::Command::new(assert_cmd::cargo::cargo_bin!("runtime-builder"));
    cmd.args([
        "typeexport",
        "--path-prefix",
        &cad_source,
        "--process-file",
        &process_file,
        "--autogen-dir",
        &autogen_dir,
        "--define",
        "ELECTROTECH",
        "--define",
        "CUSTOM_FLAG",
    ]);
    cmd.assert().success();

    let buildmode = fs::read_to_string(Path::new(&autogen_dir).join("buildmode.inc")).unwrap();
    assert_eq!(buildmode, "{$define ELECTROTECH}\n{$define CUSTOM_FLAG}\n");
}
